#server:
#  port: 8000
#  servlet:
#    context-path: /
#
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#
#cos:
#  key: cos12345

server:
  port: 8000
  servlet:
    context-path: /


spring:
  application:
    name: blog

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    defer-datasource-initialization: true

cos:
  key: cos12345