server:
  port: 8000
  servlet:
    context-path: /blog


spring:
  application:
    name: blog

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    defer-datasource-initialization: true